
BLENDER="F:\steam game\steamapps\common\Blender\blender.exe"
DIST=../dist

all : \
    $(DIST)/zoo_nolink.pnct \
    $(DIST)/zoo_nolink.scene \

$(DIST)/zoo_nolink.scene : zoo_nolink.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "zoo_nolink.blend:Main" "$(DIST)/zoo_nolink.scene"

$(DIST)/zoo_nolink.pnct : zoo_nolink.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "zoo_nolink.blend:Main" "$(DIST)/zoo_nolink.pnct" 
